### ISSUE TITLE
Error trying to 'upload' data to server

### ISSUE THREAD

**Issue by jamesbarwick** [emiloberg/liferay-ddmtool#8]
I did a 'download', then turnaround and immediately try an 'upload'.  I receive the error:

Could not extract Language Type from filename

on this file:

journal/structures/Basic Web Content - 6.2.3.1.xml

How's the best way to work around this?

**Comment by emiloberg** [comment]
Best way to work around this would be me writing better code...

Just pushed [a fix](https://github.com/emiloberg/liferay-ddmtool/commit/2e496c31cb1c4ef1242e70feb293ffc592063b16). Update the DDM Tool and you should be good to go! Please let me know it it's working or the error still persists.

**Comment by jamesbarwick** [comment]
Hey...seems to work just fine.  No more error message.  But, I'm too dim to know what I'm doing yet (a very very noob).  

By the way, sorry to ask...you don't have to answer...but what is the best way to jump start a theme development.  I've read all the blogs and training and have created some 'dummy themes', but I'm really trying to find the best way to start (even pay someone to do it for me).  Do you know any good freelancers?

**Comment by emiloberg** [comment]
Well I work with @monator, we're a full time Liferay consultancy and partner. But, getting started with theming shouldn't be that hard. 

Hit me on Skype: `emil.oberg`, Google Chat: `emil.oberg gmail.com` or email me at: `emil.oberg  monator.com` and I'll we'll see if I can point you in the right direction. 

Btw, if you're looking at theme development, you probably want to take a look at this small development tool to help you with that: https://github.com/emiloberg/Liferay-Instant-Deploy-Theme-Changes-Gulp-Script

**Comment by jamesbarwick** [comment]
Emil,

Got that running just fine.  (Instant theme deploy).  However, LiveReload isn’t working.  I have the safari plugin.  I see the livereload in the <head> script.  I see it “connected” (that is to say, when i don’t have the gulp running it says ‘can’t connect’ and when it is running it does not error….but….there is no “live reload” as I always need to refresh to see any change (even simple color changes).  The Gulp script does copy the modified files to the destination just fine when I hit ‘save’…but that’s it….which in itself is a great time saver.

By the way, I spent some money on LiveReload for Mac https://itunes.apple.com/us/app/livereload/id482898991?mt=12 https://itunes.apple.com/us/app/livereload/id482898991?mt=12  , but I haven’t really gotten that to work either….haven’t really tried…

I’d love to chat a bit more about how to get started…and even talk to you about consulting work.

We are a ‘start-up’ company….presently working on round 1 funding.   In the middle of re-writing from scratch our software from CakePHP to Liferay. (I’m not a Cake person either….but I do have 15 years PHP experience).  I inherited the CakePHP CMS and after careful evaluations…decided to move to Liferay.

Couple of things concern me about Liferay
- speed (or lack thereof)
- memory footprint (it’s huge…do I need 16GB?  48GB?….when our Cake program runs in 512MB?)

I’m running the platform on Ubuntu 14.04 on Microsoft Azure at http://teams.execuvite.com http://teams.execuvite.com/ I have done some tuning on the Java Garbage collecting, cached all the javascript and themes, and removed some servlet filters (per the Liferay tuning blog).  But, it’s still dog slow.  Could be Azure…I found an interesting article comparing AWS, Azure, Google Compute.

Although I don’t have any real interest to code portlets and services and hooks myself, I am very concerned that the company we’re talking to to do the coding will use the proper approach and methods for Liferay.

(e.g…should I just be doing everything with DDL and Web Content and Display templates?).  I gotta support 1,000,000 users eventually…

Any thoughts?

Thanks for listening!

Regards,

James Barwick, CTO
Execuvite Pte Ltd

**Comment by emiloberg** [comment]
As for the LiveReload stuff not working as it should, it's kinda hard to debug without being in front of the computer, but have you tried the Safari or Firefox extension? Are those working? Can we rule out Chrome being the problem?

As Liferay goes, what you've to realize is that Liferay is an _enterprise_ portal. CakePHP is a PHP Framework. A better comparison would be products from like Oracle WebSphere, SAP, etc. Just check the [Gartner Magic Quadrant](https://www.liferay.com/web/bryan.cheung/blog/-/blogs/liferay-s-thoughts-on-the-2014-gartner-magic-quadrant-for-horizontal-portals), we're looking at IBM, Oracle, Microsoft, SAP, IBM and Liferay.

So in short, to answer your questions: Yeah, you're gonna need powerful machines, no doubt about it. And yeah, you can get Liferay blazing fast no doubt about it. However, as this is an enterprise portal platform, it's a little more than just changing an apache setting which you might be used to. I'm trying to keep away from doing sysop things so I'm not really the person to ask on how to do it, but that it can be done - that I know. There's a lot of _big_ Liferay installations. Your 1 000 000 won't be breaking any records.

As for DDL/WebContent/ADT/etc goes. Can't really answer that, I've no idea what you want to achieve, but generally I'd say that those things combined are powerful for _displaying_ data.

**Comment by emiloberg** [comment]
Reason for _me_ to be working with Liferay is because I 1) Like working with large scale IT systems, and, 2) Like working with a tool which enables me to do really rapid development and deployment.

**Comment by jamesfalkner** [comment]
> Although I don’t have any real interest to code portlets and services and hooks myself, I am very concerned that the company we’re talking to to do the coding will use the proper approach and methods for Liferay.
> (e.g…should I just be doing everything with DDL and Web Content and Display templates?).  I gotta support 1,000,000 users eventually…

This is an excellent question - I am a big fan of DDL/WebContent Templates/ADT/FreeMarker because it lets me get stuff done real fast, etc. But it is NOT a replacement for real enterprise web development, it doesn't replace Java or the need for high-scale transactional secure highly available backends (and other "-ilities"). But for my use cases it works great because it scales _enough_ for me and it ultimately IS backed by a "high scale transactional secure highly available backend" i.e. Liferay :)

Anecdotally, I can tell you that we have customers and public-facing sites that use it for more than prototyping, and have set up development environments and source code management and continuous deployment environments for it (using tools like what @monator provides, which BTW, is really cool) so they're not "copying and pasting into a text editor" all the time when coding their apps. But it's not for everyone.

I also agree 100% with Emil as far as performance. There is also tooling like [Liferay Connected Services](https://www.liferay.com/products/liferay-connected-services) or APM tools that can help tuning beyond the easy stuff. Liferay by default requires 2GB of memory, but most production sites require more. Certain things (at least in 6.2) tend to impact memory requirements more than others, for example deploying 100 plugins needs more memory than deploying 1 plugin that does 100 things. Something you can't tune for without knowing exactly what your production characteristics are for.

[Full Disclosure: I work for Liferay and am it's open source community manager]
